/*
  -------------------------------------------------------
   This file was generated by JParser
 
   Do not make changes to this file
  -------------------------------------------------------
*/
package jolt;

import com.github.xpenatan.jparser.loader.JParserLibraryLoader;
import com.github.xpenatan.jparser.loader.JParserLibraryLoaderListener;

/**
 * @author xpenatan
 */
public class JoltLoader {

    /*
      [-JNI;-NATIVE]
              #include "JoltCustom.h"
    */
    public static void init(JParserLibraryLoaderListener listener) {
        System.out.println("JoltLoader Oct 7, 2025");
        JParserLibraryLoader.load("jolt", listener);
    }

    /**
     * Not compatible with the web
     */
    public static void initSync(JParserLibraryLoaderListener listener) {
        System.out.println("JoltLoader Oct 7, 2025");
        JParserLibraryLoader.loadSync("jolt", listener);
    }
}
