name: Build Snapshot

on:
  push:
    branches:
      - "master"

jobs:
  build-and-upload:
    uses: ./.github/workflows/build_and_upload.yml
    with:
      isRelease: false
      shouldUpload: true
    secrets: inherit
  reset-gh-pages:
    needs: build-and-upload
    uses: ./.github/workflows/reset_gh_pages.yml
    secrets: inherit

  upload-examples:
    needs: build-and-upload
    uses: ./.github/workflows/workflow_call_upload_demos_pages.yml
    secrets: inherit

  reset-gh-pages-after:
    needs: build-and-upload
    uses: ./.github/workflows/reset_gh_pages.yml
    secrets: inherit