name: Dispatch Build

on:
  workflow_call:

env:
  CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
  CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
  SIGNING_KEY: ${{ secrets.PGP_SECRET }}
  SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  upload_demos_linux:
    name: Upload Demos
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.12.1
#        with:
#          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build OpenGL Web Samples
        run: |
          ./gradlew :examples:samples:teavm:jolt_samples_build

      - name: Build WGPU Web Samples
        run: |
          ./gradlew :examples:samples:teavm-wgpu:jolt_samples_build_wgpu

      - name: Upload OpenGL Samples to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/samples/teavm/build/dist/webapp
          destination_dir: ./gl/samples
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false

      - name: Upload WGPU Samples to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/samples/teavm-wgpu/build/dist/webapp
          destination_dir: ./wgpu/samples
          publish_branch: gh-pages
